import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';

import { FeatureToggleModule } from 'ish-core/feature-toggle.module';
import { LAZY_FEATURE_MODULE } from 'ish-core/utils/module-loader/module-loader.service';

import { AuiInitComponent } from './aui-init/aui-init.component';

@NgModule({
  /*
   * TODO: This lazy feature stuff was autogenerated. Do we need it?
   */
  imports: [FeatureToggleModule],
  providers: [
    {
      provide: LAZY_FEATURE_MODULE,
      useValue: { feature: 'aui', location: () => import('../store/aui-store.module').then(m => m.AuiStoreModule) },
      multi: true,
    },
  ],
  declarations: [AuiInitComponent],
  exports: [AuiInitComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class AuiExportsModule { }
